Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
nlp = dacy.load("da_dacy_small_trf-latest")
# or equivalently
nlp = dacy.load("small")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m nlp [38;5;241m=[39m [43mdacy[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mda_dacy_small_trf-latest[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      2[0m [38;5;66;03m# or equivalently[39;00m
[1;32m      3[0m nlp [38;5;241m=[39m dacy[38;5;241m.[39mload([38;5;124m"[39m[38;5;124msmall[39m[38;5;124m"[39m)

File [0;32m~/.local/lib/python3.10/site-packages/dacy/load.py:37[0m, in [0;36mload[0;34m(model, force, **kwargs)[0m
[1;32m     12[0m [38;5;28;01mdef[39;00m [38;5;21mload[39m(
[1;32m     13[0m     model: [38;5;28mstr[39m,
[1;32m     14[0m     force: [38;5;28mbool[39m [38;5;241m=[39m [38;5;28;01mFalse[39;00m,
[1;32m     15[0m     [38;5;241m*[39m[38;5;241m*[39mkwargs: Any,
[1;32m     16[0m ) [38;5;241m-[39m[38;5;241m>[39m Language:
[1;32m     17[0m [38;5;250m    [39m[38;5;124;03m"""Load a DaCy model as a SpaCy text processing pipeline. If the model is[39;00m
[1;32m     18[0m [38;5;124;03m    not downloaded it will also download the model.[39;00m
[1;32m     19[0m 
[0;32m   (...)[0m
[1;32m     34[0m [38;5;124;03m        >>> dacy.load("medium")[39;00m
[1;32m     35[0m [38;5;124;03m    """[39;00m
[0;32m---> 37[0m     path [38;5;241m=[39m [43mdownload_model[49m[43m([49m[43mmodel[49m[43m,[49m[43m [49m[43mforce[49m[38;5;241;43m=[39;49m[43mforce[49m[43m)[49m
[1;32m     38[0m     [38;5;28;01mreturn[39;00m spacy[38;5;241m.[39mload(path, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [0;32m~/.local/lib/python3.10/site-packages/dacy/download.py:84[0m, in [0;36mdownload_model[0;34m(model, force)[0m
[1;32m     81[0m     model [38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;124mda_dacy_[39m[38;5;132;01m{[39;00mmodel[38;5;132;01m}[39;00m[38;5;124m_trf-0.1.0[39m[38;5;124m"[39m
[1;32m     83[0m [38;5;28;01mif[39;00m model [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m models_url:
[0;32m---> 84[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m     85[0m         [38;5;124m"[39m[38;5;124mThe model is not available in DaCy. Please use dacy.models() to see a[39m[38;5;124m"[39m
[1;32m     86[0m         [38;5;241m+[39m [38;5;124m"[39m[38;5;124m list of all models[39m[38;5;124m"[39m,
[1;32m     87[0m     )
[1;32m     89[0m mdl_version [38;5;241m=[39m model[38;5;241m.[39msplit([38;5;124m"[39m[38;5;124m-[39m[38;5;124m"[39m)[[38;5;241m-[39m[38;5;241m1[39m]
[1;32m     90[0m [38;5;28;01mfrom[39;00m [38;5;21;01mspacy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutil[39;00m [38;5;28;01mimport[39;00m get_installed_models

[0;31mValueError[0m: The model is not available in DaCy. Please use dacy.models() to see a list of all models
ValueError: The model is not available in DaCy. Please use dacy.models() to see a list of all models

